// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Bunffi from "bun:ffi";
import * as Buntest from "bun:test";

let libPath = import.meta.dir + "/ffi_testlib.so";

Buntest.describe("FFI", () => {
  Buntest.test("suffix is a non-empty string", () => {
    Buntest.expect(Bunffi.suffix).toBeString();
    Buntest.expect(Bunffi.suffix).toBeTruthy();
  });
  Buntest.test("dlopen and call add()", () => {
    let lib = Bunffi.dlopen(libPath, {
      add: {
        args: [
          "i32",
          "i32"
        ],
        returns: "i32"
      }
    });
    let result = lib.symbols.add(2, 3);
    Buntest.expect(result).toBe(5);
    lib.close();
  });
  Buntest.test("dlopen and call multiply()", () => {
    let lib = Bunffi.dlopen(libPath, {
      multiply: {
        args: [
          "i32",
          "i32"
        ],
        returns: "i32"
      }
    });
    let result = lib.symbols.multiply(7, 6);
    Buntest.expect(result).toBe(42);
    lib.close();
  });
  Buntest.test("dlopen and call add_doubles()", () => {
    let lib = Bunffi.dlopen(libPath, {
      add_doubles: {
        args: [
          "f64",
          "f64"
        ],
        returns: "f64"
      }
    });
    let result = lib.symbols.add_doubles(1.5, 2.5);
    Buntest.expect(result).toBeCloseTo(4.0);
    lib.close();
  });
  Buntest.test("dlopen and call hello() returning cstring", () => {
    let lib = Bunffi.dlopen(libPath, {
      hello: {
        args: [],
        returns: "cstring"
      }
    });
    let result = lib.symbols.hello();
    Buntest.expect(result.toString()).toBe("Hello from C!");
    lib.close();
  });
  Buntest.test("ptr and toBuffer roundtrip", () => {
    let arr = new Uint8Array([
      10,
      20,
      30
    ]);
    let p = Bunffi.ptr(arr);
    let buf = Bunffi.toBuffer(p, 0, 3);
    Buntest.expect(buf[0]).toBe(10);
    Buntest.expect(buf[1]).toBe(20);
    Buntest.expect(buf[2]).toBe(30);
  });
  Buntest.test("Read module reads memory correctly", () => {
    let arr = new Uint8Array([
      42,
      0,
      0,
      0
    ]);
    let p = Bunffi.ptr(arr);
    Buntest.expect(Bunffi.read.u8(p)).toBe(42);
    Buntest.expect(Bunffi.read.u8(p, 1)).toBe(0);
  });
  Buntest.test("dlopen and call negate()", () => {
    let lib = Bunffi.dlopen(libPath, {
      negate: {
        args: ["i32"],
        returns: "i32"
      }
    });
    let result = lib.symbols.negate(42);
    Buntest.expect(result).toBe(-42);
    lib.close();
  });
  Buntest.test("CC.compile compiles C source from file", () => {
    let squarePath = import.meta.dir + "/ffi_square.c";
    let lib = Bunffi.cc({
      source: squarePath,
      symbols: {
        square: {
          args: ["i32"],
          returns: "i32"
        }
      }
    });
    let result = lib.symbols.square(9);
    Buntest.expect(result).toBe(81);
    lib.close();
  });
});

export {
  libPath,
}
/* libPath Not a pure module */
