// Generated by ReScript, PLEASE EDIT WITH CARE


let CString = {};

let JSCallback = {};

let CFunction = {};

let CC = {};

let Read = {};

export {
  CString,
  JSCallback,
  CFunction,
  CC,
  Read,
}
/* No side effect */
